init api
ComicScrip/lyon-react-mars22-p2g1-api pull request #1
Opened 2022-04-21 07:51 UTC by 01adrien

2022-04-21 08:26 UTC, ComicScrip commented on db-config.js
> +require('dotenv').config();
passer par environment.js

2022-04-21 08:34 UTC, ComicScrip requested changes

2022-04-21 08:34 UTC, ComicScrip commented on src/app.js
> +app.get('/books/boxId/:Id', (req, res, next) => {
/boxes/:idBox/books

2022-04-21 08:34 UTC, ComicScrip commented on src/app.js
> +      `SELECT id, title, author, isbn, editions, publication_year, pages_nbr, synopsis, picture, note, box_number, cond, to_borrow, to_delete, out_of_stock FROM book WHERE box_number = ${req.params.I
attention, injection SQL

2022-04-21 08:34 UTC, ComicScrip commented on src/app.js
> +app.get('/books/isbn/:isbn', (req, res, next) => {
/books/:isbn

2022-04-21 08:34 UTC, ComicScrip commented on src/app.js
> +        axios
sauvegarder le livre issu de l'API google en BDD pour l'avoir au prochain coup

2022-04-21 08:34 UTC, ComicScrip commented on src/app.js
> +app.post('/book', (req, res, next) => {
/books

2022-04-21 08:34 UTC, ComicScrip commented on src/app.js
> +app.put('/books/id/:id', (req, res) => {
/books/:id

2022-04-24 10:03 UTC, ComicScrip requested changes

2022-04-24 10:03 UTC, ComicScrip commented on src/app.js
> +app.get('/books/:isbn/:boxId/:note/:cond', (req, res, next) => {
ça me semble un peu étrange de mettre d'autres paramètres que l'isbn ici. Quel est le cas d'utilisation ?

2022-04-24 10:03 UTC, ComicScrip commented on src/app.js
> +        res.status(200).json([book.author, book.editions]);
on ne devrait pas renvoyer de tableau sur une route détails

2022-04-24 16:12 UTC, 01adrien commented on src/app.js
> +app.get('/books/:isbn/:boxId/:note/:cond', (req, res, next) => {
C'est pour faire passer ces infos en base de données

2022-04-26 15:30 UTC, ComicScrip approved these changes

2022-04-26 15:30 UTC, merged